"""
Constants Module
================
Constantes centralizadas para todos los módulos
"""

import numpy as np

# Mask blur sizes
MASK_BLUR_SMALL = (5, 5)
MASK_BLUR_MEDIUM = (15, 15)
MASK_BLUR_LARGE = (21, 21)

# Blending constants
DEFAULT_PYRAMID_LEVELS = 6
FFT_COLOR_BLEND_FACTOR = 0.2
ADVANCED_BLEND_FFT_WEIGHT = 0.4
ADVANCED_BLEND_POISSON_WEIGHT = 0.6

# Seamless cloning
SEAMLESS_DILATE_SIZE = 5

# Color correction
HISTOGRAM_WEIGHT = 0.4
LAB_WEIGHT = 0.6
MASK_EXPONENT = 1.5
SURROUNDING_MASK_SIZE = 151
LUMINOSITY_BLEND_FACTOR = 0.7

# Quality enhancement
SHARPNESS_THRESHOLD = 100
CONTRAST_THRESHOLD = 30
UNIFORMITY_THRESHOLD = 0.15

# Post-processing
DETAIL_FINE_WEIGHT = 0.6
DETAIL_MEDIUM_WEIGHT = 0.3
DETAIL_COARSE_WEIGHT = 0.1

# Skin tone detection (LAB color space)
SKIN_TONE_A_MIN = 120
SKIN_TONE_A_MAX = 150
SKIN_TONE_B_MIN = 130
SKIN_TONE_B_MAX = 170

# Quality enhancement - Sharpness
SHARPNESS_BASE_WEIGHT = 0.85
SHARPNESS_ENHANCE_WEIGHT = 0.15
SHARPNESS_COMPARISON_FACTOR = 1.1
SHARPNESS_KERNEL_STRONG = np.array([[-0.15, -0.4, -0.15],
                                    [-0.4,  2.3, -0.4],
                                    [-0.15, -0.4, -0.15]])
SHARPNESS_KERNEL_MEDIUM = np.array([[-0.1, -0.2, -0.1],
                                    [-0.2,  1.2, -0.2],
                                    [-0.1, -0.2, -0.1]])
SHARPNESS_KERNEL_ADAPTIVE = np.array([[-0.2, -0.5, -0.2],
                                      [-0.5,  3.4, -0.5],
                                      [-0.2, -0.5, -0.2]])
SHARPNESS_WEIGHT_MEDIUM = 0.1

# Quality enhancement - Contrast
CONTRAST_MULTIPLIER = 1.12

# Quality enhancement - Details
DETAIL_WEIGHT_FINE = 0.5
DETAIL_WEIGHT_MEDIUM = 0.3
DETAIL_WEIGHT_COARSE = 0.2
DETAIL_APPLY_WEIGHT = 0.15
PRESERVE_DETAIL_WEIGHT = 0.15

# Quality enhancement - Feature enhancement
FEATURE_ENHANCE_WEIGHT = 0.25

# Advanced enhancements
SUPER_RESOLUTION_SCALE = 1.5
TEXTURE_PRESERVATION_WEIGHT = 0.3
EXPRESSION_PRESERVATION_WEIGHT = 0.4
EDGE_AWARE_FILTER_SIZE = 5
FREQUENCY_ENHANCEMENT_WEIGHT = 0.3
ADAPTIVE_QUALITY_TARGET = 0.9
ADAPTIVE_QUALITY_MAX_ITERATIONS = 5

# Advanced enhancements - Extended
MULTI_SCALE_ENSEMBLE_WEIGHT_1 = 0.35
MULTI_SCALE_ENSEMBLE_WEIGHT_2 = 0.35
MULTI_SCALE_ENSEMBLE_WEIGHT_3 = 0.30
PROGRESSIVE_QUALITY_STEPS = 3
TEXTURE_SYNTHESIS_WEIGHT = 0.25
PERCEPTUAL_OPTIMIZATION_ITERATIONS = 3
REGION_ADAPTIVE_SIZE = (128, 128)
REGION_ADAPTIVE_OVERLAP = 32
FINAL_QUALITY_TARGET = 0.92

# Advanced enhancements - Ultra
ATTENTION_ENHANCEMENT_WEIGHT = 0.3
GRADIENT_BOOSTING_ITERATIONS = 3
GRADIENT_BOOSTING_LEARNING_RATE = 0.1
NEURAL_STYLE_PRESERVATION_WEIGHT = 0.3
COLOR_HARMONY_HUE_WEIGHT = 0.3
COLOR_HARMONY_SAT_WEIGHT = 0.2
COLOR_HARMONY_VAL_WEIGHT = 0.15
ADAPTIVE_SHARPENING_STRONG_WEIGHT = 0.15
ADAPTIVE_SHARPENING_MEDIUM_WEIGHT = 0.25
ADAPTIVE_SHARPENING_TOTAL_WEIGHT = 0.4
ULTRA_FINAL_QUALITY_TARGET = 0.94

# Advanced enhancements - Ultimate
PERCEPTUAL_LOSS_SHARPNESS_WEIGHT = 0.6
PERCEPTUAL_LOSS_TEXTURE_WEIGHT = 0.4
PERCEPTUAL_LOSS_CORRECTION_WEIGHT = 0.3
DYNAMIC_QUALITY_MIN = 0.85
DYNAMIC_QUALITY_MAX = 0.98
DYNAMIC_QUALITY_MAX_ITERATIONS = 8
ADVANCED_ENSEMBLE_QUALITY_WEIGHTS = [0.4, 0.3, 0.3]  # sharpness, contrast, texture

# Advanced enhancements - Extreme
MULTI_SCALE_ATTENTION_SCALES = [0.5, 1.0, 2.0]
ADVERSARIAL_ENHANCEMENT_WEIGHT = 0.4
FEATURE_PRESERVING_SCALE = 1.5
DEEP_FEATURE_EDGE_WEIGHT = 0.3
DEEP_FEATURE_TEXTURE_WEIGHT = 0.4
DEEP_FEATURE_GRAD_WEIGHT = 0.3
DEEP_FEATURE_MATCH_WEIGHT = 0.5

# Advanced enhancements - Neural Learning
NEURAL_STYLE_TRANSFER_WEIGHT = 0.3
META_LEARNING_SHARPNESS_THRESHOLD = 50
META_LEARNING_CONTRAST_THRESHOLD = 20
ENSEMBLE_LEARNING_DIVERSITY_WEIGHT = 0.3
ENSEMBLE_LEARNING_QUALITY_WEIGHTS = [0.4, 0.3, 0.3]  # sharpness, contrast, texture

# Advanced enhancements - Frequency & Wavelet
WAVELET_ENHANCEMENT_WEIGHT = 0.3
FREQUENCY_ANALYSIS_RADIUS_INNER = 0.05
FREQUENCY_ANALYSIS_RADIUS_OUTER = 0.3
FREQUENCY_ANALYSIS_ENHANCEMENT = 0.2
SSIM_C1 = 0.01**2
SSIM_C2 = 0.03**2
SSIM_OPTIMIZATION_WEIGHT = 0.4
MULTI_RESOLUTION_SCALES = [0.25, 0.5, 1.0, 2.0]
MULTI_RESOLUTION_WEIGHTS = [0.15, 0.25, 0.35, 0.25]

# Advanced enhancements - Filtering & Artifacts
GUIDED_FILTER_RADIUS = 5
GUIDED_FILTER_EPS = 0.01
EDGE_PRESERVATION_CANNY_WEIGHT = 0.4
EDGE_PRESERVATION_SOBEL_WEIGHT = 0.3
EDGE_PRESERVATION_LAPLACIAN_WEIGHT = 0.3
EDGE_PRESERVATION_BLEND_WEIGHT = 0.5
ARTIFACT_REDUCTION_VAR_PERCENTILE = 95
ARTIFACT_REDUCTION_BILATERAL_WEIGHT = 0.5
ARTIFACT_REDUCTION_MEDIAN_WEIGHT = 0.1
ARTIFACT_REDUCTION_TOTAL_WEIGHT = 0.6








