/**
 * Security Reports API Routes
 * Generate and manage security reports
 */

import { NextRequest, NextResponse } from 'next/server';
import { securityReportingManager } from '@/lib/security';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const format = searchParams.get('format') || 'json';

    let reports = securityReportingManager.getAllReports();

    if (type) {
      reports = reports.filter(report => report.type === type);
    }

    if (startDate && endDate) {
      const start = new Date(startDate);
      const end = new Date(endDate);
      reports = reports.filter(report => 
        report.generatedAt >= start && report.generatedAt <= end
      );
    }

    if (format === 'csv') {
      const csv = convertReportsToCSV(reports);
      return new NextResponse(csv, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': 'attachment; filename="security-reports.csv"',
        },
      });
    }

    return NextResponse.json({
      reports,
      stats: securityReportingManager.getReportingStats(),
    });
  } catch (error) {
    console.error('Failed to get reports:', error);
    return NextResponse.json(
      { error: 'Failed to get reports' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { action, templateId, period, generatedBy, format } = body;

    switch (action) {
      case 'generate':
        if (!templateId) {
          return NextResponse.json(
            { error: 'Template ID is required' },
            { status: 400 }
          );
        }

        const report = await securityReportingManager.generateReport(
          templateId,
          period || {
            start: new Date(Date.now() - 24 * 60 * 60 * 1000),
            end: new Date(),
          },
          generatedBy || 'api'
        );

        return NextResponse.json({ report });

      case 'export':
        if (!body.reportId) {
          return NextResponse.json(
            { error: 'Report ID is required' },
            { status: 400 }
          );
        }

        const exportData = await securityReportingManager.exportReport(
          body.reportId,
          format || 'json'
        );

        return NextResponse.json({ data: exportData });

      case 'send':
        if (!body.reportId || !body.recipients) {
          return NextResponse.json(
            { error: 'Report ID and recipients are required' },
            { status: 400 }
          );
        }

        const reportToSend = securityReportingManager.getReport(body.reportId);
        if (!reportToSend) {
          return NextResponse.json(
            { error: 'Report not found' },
            { status: 404 }
          );
        }

        const sent = await securityReportingManager.sendReport(
          reportToSend,
          body.recipients
        );

        return NextResponse.json({ success: sent });

      default:
        return NextResponse.json(
          { error: 'Invalid action' },
          { status: 400 }
        );
    }
  } catch (error) {
    console.error('Failed to process report request:', error);
    return NextResponse.json(
      { error: 'Failed to process report request' },
      { status: 500 }
    );
  }
}

function convertReportsToCSV(reports: any[]): string {
  const headers = [
    'ID',
    'Title',
    'Type',
    'Status',
    'Generated At',
    'Generated By',
    'Total Events',
    'Critical Events',
    'Threats Detected',
    'Threats Blocked',
    'Compliance Score',
    'Risk Score',
  ];

  const rows = reports.map(report => [
    report.id,
    report.title,
    report.type,
    report.status,
    report.generatedAt.toISOString(),
    report.generatedBy,
    report.metrics.totalEvents,
    report.metrics.criticalEvents,
    report.metrics.threatsDetected,
    report.metrics.threatsBlocked,
    report.metrics.complianceScore,
    report.metrics.riskScore,
  ]);

  return [headers, ...rows]
    .map(row => row.map(field => `"${field}"`).join(','))
    .join('\n');
}
